<?php

namespace App\Clients;

class ClientConstants
{

    const Field_ReceptionSearch_Index = [
        "CustName" => "",
        "Phone" => "",
        "ReceptionNo" => "",
        "FieldConsultantId" => "",
        "DoctorId" => "",
        "TmpCustRegType" => "",
        "TmpCustRegTypeMenus" => "",
        "CustStatus" => "1",
        "IsNewHospSecond" => "N",
        "IsDeal" => "",
        "DatetimeReceptionStart" => "2023-05-23",
        "DatetimeReceptionEnd" => "2023-05-23",
        "Section" => "",
        "CMediaSourceType" => "",
        "CMediaSource" => "",
        "ReceptionEmpId" => "",
        "CustCardNo" => "",
        "Birthdatestart" => "",
        "Birthdatesend" => "",
        "CardType" => "",
        "ServiceAssistantId" => "",
        "RepresentativeId" => "",
        "CustLabelId" => "",
        "CustLabelMenus" => "",
        "isSearch" => "1",
        "pageSize" => "9999",
        "pageCurrent" => "1",
        "orderField" => "",
        "orderDirection" => "",
        "total" => "",
    ];

    const TEMP_API_BASE_PARAMS = [
        "DatetimeRegStart" => "",
        "DatetimeRegEnd" => "",
        "CustName" => "",
        "Phone" => "",
        "Sex" => "",
        "MediaSourceType" => "",
        "MediaSource" => "",
        "CreatedBy" => "",
        "TmpCustRegType" => "",
        "TmpCustRegTypeMenus" => "",
        "LastRecallDateStart" => "",
        "LastRecallDateEnd" => "",
        "HaveAfterCall" => "",
        "PlanRecallEmp" => "",
        "SalesConsultantId" => "",
        "IsPhone" => "",
        "RecallCountMin" => "",
        "RecallCountMax" => "",
        "DatetimeArriveStart" => "",
        "DatetimeArriveEnd" => "",
        "Remark" => "",
        "Province" => "",
        "City" => "",
        "Area" => "",
        "IsOrdered" => "",
        "Job" => "",
        "AttentionRemark" => "",
        "Address" => "",
        "QQ" => "",
        "WeiXinNo" => "",
        "StartAge" => "",
        "EndAge" => "",
        "LabelTypeId" => "",
        "CustLabelId" => "",
        "NoCustLabelId" => "",
        "NoCustLabelMenus" => "",
        "RecommendEmpId" => "",
        "RecommendCustName" => "",
        "RecommendCustPhone" => "",
        "RecommendCustCardno" => "",
        "TempCustComingNo" => "",
        "IncomeCapacity" => "",
        "GuestId" => "",
        "LastRecallExecuteBy" => "",
        "LastRecallFeedback" => "",
        "isSearch" => "1",
        "pageSize" => "100",
        "pageCurrent" => "1",
        "iscompay" => "0",
        "EmployeeToChannel" => "",
        "orderField" => "",
        "orderDirection" => "",
        "total" => "",
    ];

    const Reservation_TempCustInfo_Create_BASEDATA = [
        "refreshTabId" => '',
        "createType" => '',
        "custLabel" => '[]',
        "DatetimeReg" => "",
        "isAssign" => '',
        "Country" => '0',
// 回访人名字
        "PlanRecallEmps" => "",
// 回访人
        "PlanRecallEmp" => "",
// 建档人
        "CreatedBy" => "",
        "BeautySlonId" => '',
        "BeautySlonIdp" => '',
        "LabelTypeId" => '',
        "LabelId" => '',
        "LabelRemark" => '',
        "RecommendCustId" => '',
        "RecommendCustRelation" => '',
        "RecommendEmpId" => '',
        "Qq" => '',
        "WeixinNo" => '',
        "Job" => '',
        "MarriageStatus" => '',
        "TravelMode" => '',
        "Address" => '',
        "GuestId" => '',
        "Remark" => '',
    ];

}
